
{{- if .Values.loadbalancer.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
spec:
  ports:
  - name: http
    port: 8161
    targetPort: http
  - name: core
    port: 61616
    targetPort: core
  - name: amqp
    port: 5672
    targetPort: amqp
  type: LoadBalancer
  selector:
    app: {{ template "artemis.name" . }}
    release: {{ .Release.Name | quote }}
  sessionAffinity: "ClientIP"
  # Exclude unready slave nodes from DNS
  publishNotReadyAddresses: false


{{- end }}