apiVersion: v1
kind: Service
metadata:
  name: {{ include "artemis.fullname" . }}-slave
  labels:
{{ include "artemis.labels.standard" . | indent 4 }}
    component: artemis-node
spec:
  ports:
  - name: http
    port: 8161
    targetPort: http
  - name: core
    port: 61616
    targetPort: core
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: jmx
    port: 9494
    targetPort: jmxexporter
  clusterIP: None
  # Make sure DNS is resolvable during initialization.
  publishNotReadyAddresses: true
  selector:
    app: {{ template "artemis.name" . }}
    release: {{ .Release.Name | quote }}
    component: slave
