name: activemq-artemis
version: 0.0.3
apiVersion: v2
appVersion: 2.20.0-alpine
description: a multi-protocol, embeddable, very high performance, clustered, asynchronous messaging system.
keywords:
- activemq
- artemis
- messaging
- mom
- amqp
- jms
- mqtt
home: https://activemq.apache.org/artemis/
icon: https://activemq.apache.org/assets/img/activemq_logo_icon.png
sources:
- https://github.com/kubernetes/charts
- https://github.com/apache/activemq-artemis
maintainers:
- name: vromero
  email: victor.romero@gmail.com
engine: gotpl
